#!/usr/bin/env python
import sys,asyncio

def logOk(task:str):
    print(f"[  OK  ] taskmgr: 任务成功 {task}")
def logFailed(task:str):
    print(f"[FAILED] taskmgr: 任务失败 {task}")
def logStart(task:str):
    print(f"         taskmgr: 任务开始 {task}")
def log(task:str,level:str,content:str):
    print(f"         {task}: [{level}] {content}")

async def globalPatch():
    logStart("全局补丁")


async def main() -> int:
    if len(sys.argv)<2:
        print(f"用法: {__file__} <DeltaruneChinese仓库 路径>")
        return 1

    else:
        asyncio.gather(globalPatch())
    return 0

if __name__=="__main__":
    sys.exit(asyncio.run(main()))
